spring:
  devtools:
    restart:
      exclude:  public/**
      enabled:  true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml

server:
  port: 40213

liumapp:
  certificate:
    generator:
      port: 40214
      startDelay: 3000



